# Generated by Django 5.2.8 on 2025-11-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_office_local_government'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_contact', models.CharField(max_length=150)),
                ('employee_position', models.CharField(max_length=150)),
                ('employee_section', models.CharField(max_length=150)),
                ('employee_email', models.CharField(max_length=150)),
            ],
        ),
    ]
