# Generated by Django 5.2.8 on 2025-11-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=50)),
                ('leader_contact', models.CharField(max_length=150)),
                ('leader_position', models.CharField(max_length=150)),
                ('leader_email', models.EmailField(max_length=150)),
                ('leader_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
