# Generated by Django 5.2.8 on 2025-11-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=150)),
                ('notice_content', models.CharField(max_length=300)),
                ('notice_file', models.FileField(blank=True, null=True, upload_to='notices/')),
            ],
        ),
    ]
