# Generated by Django 5.2.8 on 2025-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_published_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
