# Generated by Django 5.2.8 on 2025-11-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notice_notice_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_content',
            field=models.TextField(),
        ),
    ]
